### ISSUE TITLE
Sort by Last Modified Time instead of quality of match

### ISSUE THREAD

**Issue by brandonhorst** [seongjaelee/notational-velocity#1]
NV always sorts by File Modified Time (`fs.statSync(file).mtime`), rather than making guesses about the quality of the search. I find this to be a more helpful metric, and would likely also improve search performance.

I'd be happy to implement this, if you'll accept it. Perhaps as a config flag?

**Comment by seongjaelee** [comment]
This is so rudimentary project, so I'm greatful for your visit. I really don't mind, and thanks for your comment. (Even though I guess you already implemented your own version by this time.)

**Comment by seongjaelee** [comment]
Meh,  I'll do it.
