### ISSUE TITLE
Indexation of existing files and subfolders

### ISSUE THREAD

**Issue by wolfromm** [seongjaelee/notational-velocity#12]
Hi, maybe I'm wrong but it seems it doesn't index existing files in the notes folder. Right? And so it shouldn't be possible to have subfolders (which is also a fonctionnality missing in nvAlt).

Edit: Sorry it works. Files should not be .txt but .md. Very good package :-)

**Comment by seongjaelee** [comment]
Cool! Adding which extension to include in the config would be also good thing to do next (e.g., .markdown, .md, .txt...).
