### ISSUE TITLE
If the search finds a file starting with a lowercase letter, you can't start a file with an uppercase letter

### ISSUE THREAD

**Issue by juranta** [seongjaelee/notational-velocity#14]
For instance, if I want to create a new file called "Hello world" with uppercase first letter, if the search bar finds a file "hello" with a lowercase first letter, the search bar will change to lowercase. That is, if my intention is to create a file with an uppercase first letter, that lowercase file will prevent my from doing so.

**Comment by seongjaelee** [comment]
Thanks! This is an important issue. I started working on it.
