### ISSUE TITLE
Deleting Notes

### ISSUE THREAD

**Issue by aewing** [seongjaelee/notational-velocity#18]
Unless I'm missing something there's currently no way to delete a note outside of manually deleting the file. I think the most intuitive way to handle this (aside from pressing the delete key with a note selected + confirmation) is when closing a note with no content, the file should be removed.

**Comment by seongjaelee** [comment]
This is a wonderful feature. Sorry for my late response. It is now applied to the new version v0.8.0 (nvatom, not notational-velocity).
