### ISSUE TITLE
Allow hotkey to work when Atom window is not in focus

### ISSUE THREAD

**Issue by benbalter** [seongjaelee/notational-velocity#20]
I'm not sure if it's possible to do within Atom, but it'd be awesome if the hotkey were global, rather than specific to Atom.

**Comment by seongjaelee** [comment]
This is a great idea (I think I should also consider using it). However this is not the scope of this project, but the scope of OS/atom. I think if it is OS-specific, we can launch another project doing it. For OSX, we can make Atom to access a permission on accessibility.

**Comment by seongjaelee** [comment]
I think this is out of this atom-package scope. Closing it. If you have a good reference atom package that does this feature, please let me know and reopen this issue. Thanks!
