### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by zettler** [seongjaelee/notational-velocity#21]
> runas@2.0.0 install C:\Users\User2\AppData\Local\Temp\apm-install-dir-11574-4348-qvzink\node_modules\notational-velocity\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\User2\AppData\Local\Temp\apm-install-dir-11574-4348-qvzink\node_modules\notational-velocity\node_modules\pathwatcher\node_modules\runas>node "C:\Users\User2\AppData\Local\atom\app-1.0.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\User2\AppData\Local\atom\app-1.0.3\resources\app\apm\bin\\node.exe" "C:\Users\User2\AppData\Local\atom\app-1.0.3\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\User2\.atom\.apm\.apmrc" "--userconfig" "C:\Users\User2\.atom\.apmrc" "install" "C:\Users\User2\AppData\Local\Temp\d-11574-4348-dccaro\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by seongjaelee** [comment]
It should be fixed in 0.2.0 with #24. If the problem still appears, please reopen this issue.
