### ISSUE TITLE
Incompatible native modules that this package depends on.

### ISSUE THREAD

**Issue by lexicalunit** [seongjaelee/notational-velocity#27]
I'm getting an incompatible package error after installing nvatom. I've copy/paste the error below.
## Version Information

``` shell
$ apm --version
apm  1.0.4
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.1
```
## Incompatible Package Error

> The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.
> 
> Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 41.0.2272.76 and Node 1.5.1.
> 
> The packages listed should now ship versions of these native modules that are compatible with Node 1.5.1.
> 
> Updates for these packages may already be available that resolve this issue.
> 
> If no update is available you may want to notify the package author that their package isn't supported in Atom 1.0.11 because of the Chrome 41.0.2272.76 and Node 1.5.1 upgrade.
> 
> If you think a package is listed here and should no longer be, click the button below to reload Atom and recheck all packages.
### Nvatom 0.8.0

> Listed below are the incompatible native modules that this package depends on.
> - fsevents@0.3.8
>   - Error message: Module version mismatch. Expected 43, got 14.

**Comment by seongjaelee** [comment]
This is an error that had been bugging me for a week. Hmmm...

Did you just install the package from Atom? Or did you `git clone`-ed the repository and `apm build`-ed it? If the later, try to delete node_modules and run `apm build` and `apm rebuild`. In the error message box from Atom, there is some button like "reload atom" within the message box. When I clicked it after callling `apm build/rebuild`, it was gone.

If it's still not working, which OSX are you using? Are you using the most recent atom version (1.0.11)?

**Comment by jonmagic** [comment]
I'm asking for help in the Atom chat room on Slack and if that doesn't pan out I'm going to ping one of the Atom devs directly for help (I just so happen to work with them at GitHub :grin:).

**Comment by seongjaelee** [comment]
Thanks very much Jonathan! :smile:

To clarify, I don't experience the problem anymore. Mine was #24. It happend mostly during `apm test`, but when I was playing with `npm` and `apm`, sometimes I got the error even on the atom editor. But it got easily removed from atom editor when I rebuilt the package only using `apm`.

I'll be waiting for replies from lexicalunit.

**Comment by lexicalunit** [comment]
I'm running OS X 10.10.4, also I'm using the latest Atom version:

```
$ atom --version
1.0.11
```

@seongjaelee I tried repo cloning first, then the `apm install` method second. I opened the ticket after I saw the issue come up from the `apm install` method.

`apm build` is an invalid command:

```
$ apm build
Unrecognized command: build
```

Did you mean `npm install`? Here's my log from running that command (after cloning the repo into `~/.atom/packages`):

```
> npm install
|
> fsevents@0.3.8 install /Users/atroschinetz/.atom/packages/nvatom/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
underscore-plus@1.6.6 node_modules/underscore-plus
└── underscore@1.6.0

fs-plus@2.8.1 node_modules/fs-plus
├── rimraf@2.2.8
├── async@0.2.10
└── mkdirp@0.3.5

docquery@1.1.0 node_modules/docquery
├── minimist@1.2.0
├── underscore@1.8.3
├── tilde-expansion@0.0.0 (etc-passwd@0.0.1)
└── lunr@0.5.12

atom-space-pen-views@2.1.0 node_modules/atom-space-pen-views
├── fuzzaldrin@2.1.0
└── space-pen@5.1.1 (jquery@2.1.4, grim@1.4.2)

chokidar@1.0.5 node_modules/chokidar
├── arrify@1.0.0
├── path-is-absolute@1.0.0
├── is-glob@1.1.3
├── glob-parent@1.2.0
├── async-each@0.1.6
├── is-binary-path@1.0.1 (binary-extensions@1.3.1)
├── readdirp@1.4.0 (graceful-fs@4.1.2, readable-stream@1.0.33, minimatch@0.2.14)
├── anymatch@1.3.0 (micromatch@2.2.0)
└── fsevents@0.3.8 (nan@2.0.9)
```

This results in the error I reported. I was also able to run `apm rebuild`, here's the log:

```
$ apm rebuild
Rebuilding modules ✓
```

After doing that I still see the incompatibility error.

**Comment by seongjaelee** [comment]
@lexicalunit Yes, it is `apm install`, as you said. I thought mixing apm and npm is the problem, 'cause for my case, apm's npm version and npm's version didn't match.

So, did you just install the package from Atom, not cloning the git repository? If so, you don't have to run apm/npm commands at all from the beginning.

**Comment by jonmagic** [comment]
Today I updated Atom to 1.0.12 and after that my local development copy of nvatom stopped working with the fsevent module version mismatch error. It recommended I rebuild so I tried that but it failed.

I then uninstalled my local development copy of the nvatom package and reinstalled the package from the Install section in Settings and it works perfectly now. I haven't been able to reproduce the issue since then.

**Comment by seongjaelee** [comment]
I am in the same situation. When I click the red bug icon on the bottom right, it shows the following error messages.

```
nvatom 0.8.1.

/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/seongjae/.atom/.apm/.apmrc" "--userconfig" "/Users/seongjae/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seongjae/github/notational-velocity/npm-debug.log
```

There is a "Rebuild Packages" button on the top right, but when I click it, it gives me a "Rebuild Failed" message.

**Comment by seongjaelee** [comment]
``` sh
seongjae:notational-velocity apm install; apm rebuild; apm test;
Installing modules ✓
Rebuilding modules ✓
[85686:0917/204132:INFO:renderer_main.cc(200)] Renderer process started
[85682:0917/204132:INFO:CONSOLE(46)] "Window load time: 330ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (46)
[85682:0917/204133:INFO:CONSOLE(755)] "Failed to require the main module of 'nvatom' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /Applications/Atom.app/Contents/Resources/app.asar/src/package.js (755)
F[85682:0917/204133:INFO:CONSOLE(755)] "Failed to require the main module of 'nvatom' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /Applications/Atom.app/Contents/Resources/app.asar/src/package.js (755)
F

nvAtom
  when the nvatom:toggle event is triggered
    it attaches and then detaches the view
      Expected null to exist.
        at [object Object].<anonymous> (/Users/seongjae/github/notational-velocity/spec/notational-velocity-spec.coffee:27:59)
        at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
        at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
        at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
        at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
        at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
        at doNTCallback0 (node.js:416:9)
        at process._tickCallback (node.js:345:13)
    it checks if we banned the default directory under packages directory
      TypeError: Cannot read property 'querySelector' of null
        at [object Object].<anonymous> (/Users/seongjae/github/notational-velocity/spec/notational-velocity-spec.coffee:48:47)
        at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
        at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
        at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
        at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
        at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
        at doNTCallback0 (node.js:416:9)
        at process._tickCallback (node.js:345:13)


Finished in 0.182 seconds
2 tests, 3 assertions, 2 failures, 0 skipped

Tests failed
```

**Comment by seongjaelee** [comment]
Hmm, I re-run the travis test, but it passes, even with atom 1.0.13. I guess there must be some cache hidden somewhere outside node_modules.
https://travis-ci.org/seongjaelee/nvatom/builds/80760310

**Comment by seongjaelee** [comment]
Hmm, I deleted .atom/.apm, .atom/.node_gyp, .atom/compile-cache, .atom/storage, nvatom/node_modules but it still gives the same problem.

**Comment by seongjaelee** [comment]
I deleted my nvatom from .atom/packages, installed it again. It still gave the red bug icon on the bottom right.
I rebuilded it by using the botton on the top right, and then reloaded atom, and then the error is gone.

**Comment by seongjaelee** [comment]
@lexicalunit, do you still have the problem? If I don't hear from you for a week, I'll close this issue "not reproducible". You can try delete-install-rebuild-reload as described above... I cannot reproduce it again, but it seems like it is related to some cache outside of the package.

**Comment by lexicalunit** [comment]
Weird. Installing from the Settings panel within Atom seems to work fine.

It's just installing manually from git or installing using apm that seems to have issues for me.

**Comment by lexicalunit** [comment]
Actually, I just got it to work installing manually from git. :+1:
