### ISSUE TITLE
Integrate search view with fuzzy finder?

### ISSUE THREAD

**Issue by ghost** [seongjaelee/notational-velocity#36]
It occurred to me that since Atom already has a [fuzzy-finder](https://github.com/atom/fuzzy-finder) view accessible via `cmd-t/cmd-p` would it make sense (or even be possible) to integrate the `nvatom` search view into the fuzzy-finder? Having an extra `nvatom` specific view seems to be a duplication of functionality.

As a user, I already access files all the time using `cmd-t` so when I'm working on my notes, it would be awesome to continue to use the same key-bindings. It would be nice to have the fuzzy-finder switch from searching by file-name only, to the nvatom feature of also searching within the note body.

Perhaps `nvatom` could use a 'smart' approach where fuzzy-finder integration only occurs when the user is working within the notes root directory. This allows for normal fuzzy-finder operation when using Atom for writing code.

Thanks!

**Comment by seongjaelee** [comment]
Heh, I didn't know that feature but it looks like this is really convenient (also the popup window looks nicer with a smaller margin).

> Perhaps nvatom could use a 'smart' approach where fuzzy-finder integration only occurs when the user is working within the notes root directory. This allows for normal fuzzy-finder operation when using Atom for writing code.

I guess you meant the other way? In other words, `cmt-t` triggers fuzzy-finder when outside of note root directory, while it triggers nvatom when within the note root directory.

**Comment by ghost** [comment]
> I guess you meant the other way?

Well, my question is can you integrate `nvatom` within fuzzy-finder window? So `cmd-t` always triggers fuzzy-finder, but `nvatom` injects itself into fuzzy-finder only within note root directory. I am wondering if there is an advantage to hooking into fuzzy-finder, instead of the current `nvatom` search view. Eliminate the extra search view code and just depend on fuzzy-finder to do the display of notes titles & bodies, and modify it only when in notes root.

Or perhaps another alternative is to just remap the `cmd-t` when inside the notes roote, as you're suggesting, and keep the duplicate functionality.

**Comment by seongjaelee** [comment]
To understand your intention more clearly, I need to ask more questions - what will be the difference (from user's view) between the first "injection" idea and the "conditional remap" idea?

**Comment by ghost** [comment]
Nothing, if the views look the same, and the feel is the same.

However to me it seems wasteful and potentially problematic to have duplication of effort by keeping 2 different sets of code to serve the same functionality. Perhaps I am thinking about this the wrong way. I tend to think very DRY (don't repeat yourself) - perhaps this doesn't apply in this situation.

**Comment by seongjaelee** [comment]
I get your point. Still, it is not the same functionality (besides file name search vs. file name + context search), even for the UI perspective. For example, search query autocomplete is a different from FuzzyFinder. Also... to inject into FuzzyFinder, somebody needs to check if the code does not break whenever we update FuzzyFinder (I'm thinking of overriding some of the features onto FuzzyFinder. If we inject, then we need to test our package whenever they update their package.). That is too much work for a couple of maintainers.

I looked at their code, and it seems like there are more ((FuzzyFinder - nvAtom) ∪ (nvAtom - FuzzyFinder)) than (FuzzyFinder ∩ nvAtom). (I noticed that they have several cool features I wanted to implemented). I will keep following their code, adding some of their features into our code. If diffs of two packages becomes pretty small, then we might consider migratiion, merging or overriding.

**Comment by brandonhorst** [comment]
From a UX perspective, I would not want nvatom to override the built in cmd-t cmd-p functionality. That betrays the user's expectations. There may well be times when you want to open a file with the fuzzy search rather than the NV functionality, and it would be a shame to remove that ability.

**Comment by ghost** [comment]
>  it is not the same functionality (besides file name search vs. file name + context search), even for the UI perspective. 

Ah ok, I was not sure.

> (I noticed that they have several cool features I wanted to implemented). I will keep following their code, adding some of their features into our code.

Cool, at least this issue was not a waste of time. :smile: 

> From a UX perspective, I would not want nvatom to override the built in cmd-t cmd-p functionality. That betrays the user's expectations.

You're right. I should have thought of this. If the user wants, they can re-bind either `cmd-p` or `cmd-t` to the `nvatom` search view if they don't like the current 3-key binding.
