### ISSUE TITLE
nvAtom Github Markdown Grammar settings area appears twice

### ISSUE THREAD

**Issue by ghost** [seongjaelee/notational-velocity#39]
The settings section titled "nvAtom Github Markdown Grammar" appears twice.

**Comment by seongjaelee** [comment]
Mmm... I didn't notice that settings section. I don't want to reveal it... nor override the settings from GFM.
Anyway... in my Atom, it is repeated 2 times. I'll start working on this issue. Thanks!

**Comment by ghost** [comment]
It now only appears twice.

**Comment by ghost** [comment]
I'm seeing the same thing. The section `nvAtom Github Markdown Grammer` appears twice in settings on Atom 1.5.3 with nvAtom 0.9.3.

**Comment by humanfactors** [comment]
Appearing twice for me also. It appears it's listed twice in the compilers as well.
