### ISSUE TITLE
Deleting a file outside of nvatom causes an uncaught exception.

### ISSUE THREAD

**Issue by Zettt** [seongjaelee/notational-velocity#43]
I get this error regularly in Atom.

Basic setup:  
I use `~/Desktop` as my nvatom directory. This means that I sometimes delete files outside of Atom, and therefore nvatom. This seems to cause an issue where I can't close the tab of a non-existing file anymore, throwing the error below.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.2
**Thrown From**: [nvatom](https://github.com/seongjaelee/nvatom) package, v0.9.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/zettt/Desktop/themen.txt'

```
At fs.js:947

Error: ENOENT: no such file or directory, unlink '/Users/zettt/Desktop/themen.txt'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:947:18)
    at Object.module.exports.autodelete (/Users/zettt/.atom/packages/nvatom/lib/notational-velocity.coffee:78:8)
    at /Users/zettt/.atom/packages/nvatom/lib/notational-velocity.coffee:48:97
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:285:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:442:17)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "remember-session",
      "autocomplete",
      "term"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "customFileTypes": {
      "source.gfm": [
        "txt",
        "markdown",
        "md"
      ]
    }
  },
  "nvatom": {
    "directory": "~/Desktop/",
    "extensions": [
      ".txt",
      ".md",
      ".csv"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
column-select, v0.2.0
command-logger, v0.23.0
editor-stats, v0.17.0
ever-notedown, v0.2.16
fountain, v0.2.0
git-log, v0.4.1
language-markdown, v0.3.1
monokai, v0.18.0
nvatom, v0.9.3
tabs-to-spaces, v0.11.1
tasks, v2.6.0
vim-mode, v0.63.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by matheo** [comment]
Seems that a watcher is needed, like it's done by the `imdone` package.

**Comment by Zettt** [comment]
@matheo Seems a maintainer is needed for this package. No response in half a year, no commit either. It's dead, Jim.

**Comment by ghost** [comment]
:sob: 

Maybe checkout this? https://github.com/viddo/atom-textual-velocity

**Comment by seongjaelee** [comment]
I checked with Atom v.1.7.2, and it does not happen anymore.
Atom automatically closes the deleted file itself, not executing autodelete.
No change is necessary.

**Comment by sahilseth** [comment]
I still see this issue

**Comment by seongjaelee** [comment]
Sorry guys. I don't have time to work on this project for a while.
If any of you want to be an admin of this, please let me know.
