### ISSUE TITLE
Configuring directory in config.cson breaks Markdown Preview

### ISSUE THREAD

**Issue by ivenhov** [seongjaelee/notational-velocity#45]
After adding 
  'nvatom':
    directory: '/path/to/your/notes'

Markdown Preview window does not display when keyboard or menu option used.
Tried with no space, single and double space before nvatom.
The end result is that either directory is not configured or Markdown Preview is not working.

**Comment by onechrisjones** [comment]
I got the same problem... It also messes with my syntax highlighting...

**Comment by xiaoxinghu** [comment]
Same problem here.

**Comment by strickinato** [comment]
I had this problem but @seongjaelee's comment in related issue: https://github.com/seongjaelee/nvatom/issues/40#issuecomment-149068451 solved it.

**Comment by seongjaelee** [comment]
This is a duplicate, so closing the issue. For intermediate solution, refer to the comment above. Thanks!
