### ISSUE TITLE
Cannot search special characters in note title

### ISSUE THREAD

**Issue by aviau** [seongjaelee/notational-velocity#51]
Hello!

I have created note with the following title: `hello @test`

Now I want to search for the note, so I type in `@test` in the search bar, but my note does not show up.

As soon as I type the @ character, all search results disapear.

**Comment by seongjaelee** [comment]
This is docQuery -> lunr's problem.
notational-velocity-view.coffee, filter: (filterQuery), return @docQuery.search(filterQuery).
If you want to search with @, go to Settings and uncheck "Enable Lunr Pipeline".

If we really really want to be improve it, we should search titles outside of lunr framework... but I don't want to.
